config/routes.rb
Rails.application.routes.draw do
  root to: 'games#home'
  devise_for :users
    resources :users, only: [:show] do
    resources :listings, only: [:index]
    resources :wishlist_items, only: [:index]
  end
  resources :listings, only: [:new, :create, :destroy] do
    resources :swaps, only: [:new, :create]
  end
  resources :wishlist_items, only: [:new, :create, :destroy]
  resources :swaps, only: [:update, :index, :edit]
  resources :games, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  include PgSearch::Model
  CONSOLES = ['Switch', 'PS4', 'Xbox One', 'PC']
  validates :title, presence: true
  validates :console, uniqueness: {
    scope: :title,
    message: "Cannot have multiples of a title on the same console"
  }, inclusion: {
    in: CONSOLES,
    message: "Not a valid console"
  }
  validates :description, presence: true
  validates :rating, presence: true

  has_many :listings, dependent: :destroy

  pg_search_scope :search_by_title_description_console_and_rating,
    against: [:title, :description, :console, :rating],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/listing.rb
class Listing < ApplicationRecord
  CONDITIONS = ['New', 'Like New', 'Good', 'Acceptable']
  belongs_to :user
  belongs_to :game
  validates :user, :game, :condition, presence: true
  validates :condition, inclusion: {
    in: CONDITIONS,
    message: "Not a valid condition"
  }
  # has_many :swaps_where_offered, inverse_of: :listing_offered
  # has_many :swaps_where_requested, source: :swaps, foreign_key: :listing_requested

  # has_many :swaps, ->(listing) { unscope(:where).where("listing_requested_id = :id OR listing_offered_id = :id", id: listing.id) }

  has_many :requested_swaps, foreign_key: 'listing_requested', class_name: 'Swap'
  has_many :offered_swaps, foreign_key: 'listing_offered', class_name: 'Swap'

  def to_label
    "#{game.title} - #{game.console}"
  end
end

app/models/swap.rb
class Swap < ApplicationRecord
  belongs_to :listing_requested, class_name: :Listing
  belongs_to :listing_offered, class_name: :Listing
  # validates :listing_offered, :listing_requested, :status, :offered_recieved, :requested_recieved, presence: true
  scope :requested_from, ->(user) { includes(:listing_requested).where('listings.user_id' => user.id) }
  scope :offered_by, ->(user) { includes(:listing_offered).where('listings.user_id' => user.id) }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :listings
  has_many :wishlist_items

  # has_many :offered_swaps, through: :listings, foreign_key: :listing_offered, source: :swaps
  validates :first_name, :last_name, :username, :city, :email, presence: true
  validates :username, :email, uniqueness: true
  validates :email, format: { with: /\A[a-z0-9.]+@[a-z]+\.[a-z]{2,3}\z/i }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :requested_swaps, through: :listings, foreign_key: 'listing_requested', class_name: 'Swap'
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validates :user, :game, :condition, presence: true
  validates :user, uniqueness: {
    scope: :game,
    message: "Cannot wish for the same game multiple times"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :city, :username, :photo, :photo_cache])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :home]

  def home
  end

  def index
    if params[:query].present?
      @games = Game.order("LOWER(title)").search_by_title_description_console_and_rating(params[:query])
    else
      @games = Game.all.limit(50).order("LOWER(title)")
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  private

  def listing_params
    params.require('listing').permit(:game_id, :condition)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
  end

  def new
    @listing = Listing.new
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to user_listings_path(current_user)
    else
      render :new
    end
  end

  private

  def listing_params
    params.require('listing').permit(:game_id, :condition)
  end
end

app/controllers/swaps_controller.rb
class SwapsController < ApplicationController
  def index
    @swaps = Swap.all
  end

  def new
    @listing = Listing.find(params[:listing_id])
    @swap = Swap.new
  end

  def create
    @swap = Swap.new(swap_params)
    @listing = Listing.find(params[:listing_id])
    @swap.listing_requested = @listing
    if @swap.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
    @swap = Listing.find(params[:id])
  end

  def update
    @swap = Listing.find(params[:id])
    if @swap.update(swap_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def swap_params
    params.require('swap').permit(:listing_offered_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @swaps = Swap.all
  end
end

app/controllers/wishlist_item_controller.rb
class WishlistItemController < ApplicationController
  def new
    @wishlist_item = WishlistItem.new
  end

  def show
    @wishlist_item = WishlistItem.find(params[:id])
  end

  def create
    @wishlist_item = WishlistItem.new(wishlist_item_params)
    @wishlist_item.user = current_user
    if @wishlist_item.save
      redirect_to user_wishlist_items_path(current_user)
    else
      render :new
    end
  end

  private

  def wishlist_item_params
    params.require('wishlist_item').permit(:game_id, :condition)
  end
end

app/controllers/wishlist_items_controller.rb
class WishlistItemsController < ApplicationController
  def index
  end

  def new
    @wishlist_item = WishlistItem.new
  end

  def show
    @wishlist_item = WishlistItem.find(params[:id])
  end

  def create
    @wishlist_item = WishlistItem.new(wishlist_item_params)
    @wishlist_item.user = current_user
    if @wishlist_item.save
      redirect_to user_wishlist_items_path(current_user)
    else
      render :new
    end
  end

  private

  def wishlist_item_params
    params.require('wishlist_item').permit(:game_id, :condition)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/home.html.erb
<div id="carouselExampleControls" class="carousel slide " data-ride="carousel">
  <div class="carousel-inner ">
      <h1 class="carousel-caption carousel-btn"><%= link_to "Browse Games" , games_path , class: "btn-red"%></h1>
    <div class="carousel-item active">
      <%= cl_image_tag 'pokemon2', alt: "alttext", class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= cl_image_tag 'reddead2', alt: "alttext", class: "d-block w-100" %>
    </div>
    <div class="carousel-item">
      <%= cl_image_tag 'zelda.png', alt: "alttext", class: "d-block w-100" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container-landing d-flex justify-content-center mt-3">
  <div class="row">
    <div class="card-landing ">
      <p><i class="fas fa-sync"></i></p>
      <h4> Swap your favourite games anywhere, anytime!</h4>
    </div>
    <div class="card-landing ">
      <p><i class="fas fa-gamepad"></i></p>
      <h4>Choose from the latest releases to old-school classics</h4>
    </div>
    <div class="card-landing">
      <p><i class="fas fa-search"></i></p>
      <h4>Find the game that fits your taste</h4>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<%# <div class="index-banner" style="background-image: url('https://i.pinimg.com/originals/f5/e9/3c/f5e93cb7fe0df0aad558bf7442631186.jpg')"></div> %>

<div class="container">
  <!--Search-->
  <div class="search-form-control form-group">
    <%= form_tag games_path, method: :get, class: "search-form d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control mx-3",
        placeholder: "Enter the name of a game"
      %>
      <%= submit_tag "Search", class: "button-blue mx-3", id:"search" %>
    <% end %>
  </div>

  <div class="row justify-content-center">
      <% @games.each do |game| %>
        <div class="col-lg-2 col-md-3 col-sm-4 col-xs-5 card p-0 m-2">
          <%= link_to "", game_path(game), class:"listing-card-link" %>
          <%= image_tag game.cover_image, alt: "alttext", class:"card-cover-image w-100"%>
          <div class="card-index-infos ml-2 p-1 pb-3">
            <h5 class="game-title pt-2"><%= game.title %></h5>
              <% if game.rating.between?(90,100) %>
              <% 5.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
            <% elsif game.rating.between?(72,89)%>
              <% 4.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <i class="fas fa-star star-black"></i>
            <% elsif game.rating.between?(60,71)%>
              <% 3.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <% 2.times do %>
                <i class="fas fa-star star-black"></i>
              <% end %>
            <% elsif game.rating.between?(51,60)%>
              <% 2.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <% 3.times do %>
                <i class="fas fa-star star-black"></i>
              <% end %>
            <% elsif game.rating.between?(0,50)%>
              <% 1.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <% 4.times do %>
                <i class="fas fa-star star-black"></i>
              <% end %>
            <% end %>
          <!--rating algo ends-->
            <p class="console-type"><%=game.console %> ・ <%= game.release_date.strftime("%b %d, %Y") %></p>
            <p class="game-description"><%=game.description.split(",").first(2).join(", ") %></p>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">
<div class="mt-5 d-flex justify-content-left">
</p>
</div>
  <div class="row justify-content-around">
    <div class="game-information col-lg-4 position-sticky">
      <h3 class="show-game-title pb-3 pt-2"> <%= @game.title %> </h3>
            <% if @game.rating.between?(90,100) %>
              <% 5.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
            <% elsif @game.rating.between?(72,89)%>
              <% 4.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <i class="fas fa-star star-black"></i>
            <% elsif @game.rating.between?(60,71)%>
              <% 3.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <% 2.times do %>
                <i class="fas fa-star star-black"></i>
              <% end %>
            <% elsif @game.rating.between?(51,60)%>
              <% 2.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <% 3.times do %>
                <i class="fas fa-star star-black"></i>
              <% end %>
            <% elsif @game.rating.between?(0,50)%>
              <% 1.times do %>
                <i class="fas fa-star star-yellow"></i>
              <% end %>
              <% 4.times do %>
                <i class="fas fa-star star-black"></i>
              <% end %>
            <% end %> <br>
      <%= image_tag @game.cover_image, alt: "alttext", class:"mt-3 mb-3", size: "300x400"%>
      <p class="console-type pb-2"><%= @game.console %> ・ <%= @game.release_date %></p>
      <p class="pb-3"><%= @game.description %></p>
    <p class="go-back pb-3 mb-2"><%=link_to games_path , class: "button-blue justify-content-center shadow-none" do %>
      <i class="fas fa-arrow-left"></i> Go Back
    <% end %>
    </div>

      <div class="justify-content-center col-lg-7" id="available-listing">
    <h3 class="show-game-title pb-3 pt-2">Available listings</h3>

    <div id="available-listing-card">
    <% @game.listings.each do |listing| %>
      <% if listing.user.username == current_user.username %>
        <%= "" %>
        <% else %>
        <div class="card-product">
          <% if listing.user.photo.filename %>
            <%= cl_image_tag listing.user.photo.url(:user_photo_main) %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dedqosv7x/image/upload/w_160,ar_1:1,c_fill,g_auto,/v1573196467/drnvl6hpigqsuxy8iqhn.jpg" %>
          <% end %>
          <div class="card-product-infos">
            <h2><%= name = listing.user.username %> </h2>
            <p class="mb-2">Condition: <%= listing.condition %> </p>
            <%= link_to "", new_listing_swap_path(listing) , class: 'listing-card-link' %>
          </div>
          <% end %>
        </div>
    <% end %>
        <div class="card-product">
        <%= link_to "", new_listing_path , class: 'listing-card-link' %>
        <div class="card-product-infos text-center" id="add-new-content">
          <i class="fas fa-plus fa-lg pb-2" id="add-plus"></i>
          <h2 class="text-center" id="list-now"> HAVE GAME? LIST NOW </h2>
        </div>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Swapsies</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="d-flex flex-column justify-content-between min-vh-100">
      <%= render 'shared/navbar' %>
    <div class="flex-grow-1">
      <%= yield %>
    </div>
      <%= render 'shared/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/listings/index.html.erb
<div class="container">
  <h1 class="find-games"> My Listed Games</h1>
  <br>

  <div class="row justify-content-left mb-4">
    <% current_user.listings.each do |listing| %>
      <div class="card-product listing-card">
        <%= image_tag listing.game.cover_image, alt: "alttext", class:"card-cover-image"%>
        <div class="card-product-infos">
          <h5 class="game-title"><%= listing.game.title %></h5>
        <!--rating algo ends-->
          <p class="console-type"><%=listing.game.console %></p>
          <p class="game-description"><%= listing.condition %></p>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to "Browse Games", games_path, class: "button-orange mr-3" %>
  <%= link_to "List Another Game", new_listing_path(current_user), class: "button-blue mr-3" %>

</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="plain-field">
  <h1 class="find-games">Create a new listing</h1>
    <%= simple_form_for [@listing] do |f| %>
    <%= f.association :game, collection: Game.all.map { |game| [game.id, "#{game.title} - #{game.console}"]}, label_method: :second, value_method: :first, input_html: { class: "select2" } %>
      <%= f.input :condition, collection: Listing::CONDITIONS %>
      <%= f.submit "List Game", class: "button-blue"%>
    <% end %>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="container">
  <div class="row align-items-center show-banner mb-4">
    <div class="col-6 "
      style="height: 300px; background-image:linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= asset_path('control.png'); %>');background-size: cover;
  background-position: center; ">

    </div>
    <div class="col-6 ">
     <h1> <%= @game.title %> </h1>
     <h2> <%= @game.console %> </h2>
     <h2> <%= @game.description %></h2>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer Elements -->

<div class="footer-main">
  <div  class="container d-flex align-items-end justify-content-around">



  <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <%= link_to "https://www.linkedin.com/in/bogdanmatei90", :target => "_blank" do %>
          <i class="fab fa-linkedin"> </i>
        <% end %>
         B. Matei
      </li>
      <li class="list-inline-item">
        <%= link_to "https://www.linkedin.com/in/taisei-yamada-b16214161", :target => "_blank" do %>
          <i class="fab fa-linkedin text-danger"> </i>
        <% end %>
         T. Yamada
      </li>
      <li class="list-inline-item">
        <%= link_to "https://www.linkedin.com/in/noah-thorne-262478112/", :target => "_blank" do %>
          <i class="fab fa-linkedin text-success"> </i>
        <% end %>
         N. Thorne
      </li>
      <li class="list-inline-item">
        <%= link_to "https://www.linkedin.com/in/edward-blundell-65197a104/", :target => "_blank" do %>
          <i class="fab fa-linkedin text-warning"> </i>
        <% end %>
         E. Blundell
      </li>
    </ul>
    <p class="footer-copyright text-center py-3">© Created by Ronpa Team - LeWagon Batch 310</p>
  </div>
</div>

  <!-- Copyright -->
<!-- Footer -->

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-lewagon fixed-top">
  <%= link_to root_path, class: "nav-link" do %>
    <div <%= "data-splitting" if params[:action] == 'home' %> class="logo-navbar">SWAPSIES</div>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to games_path, class: "nav-link" do %>
            <i class="fas fa-search"></i> Browse Games
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_listing_path, class: "nav-link" do %>
            <i class="fas fa-plus"></i> List a Game
            <% end %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.filename %>
            <%= cl_image_tag current_user.photo.url(:dashboard_avatar), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dedqosv7x/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,b_rgb:262c35/v1573196467/drnvl6hpigqsuxy8iqhn.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Swaps", user_path(current_user), class: "dropdown-item nav-link"  %>
            <%= link_to "My Listed Games", user_listings_path(current_user), class: "dropdown-item nav-link"  %>
            <%= link_to "Wishlist", user_wishlist_items_path(current_user), class: "dropdown-item nav-link"  %>
            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item nav-link"  %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item nav-link" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Make an Account", new_user_registration_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Sign In", new_user_session_path, class: " button-blue "  %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/swaps/new.html.erb
<div class="container">


  <div class="plain-field">
    <h1 class="find-games">Swap Games!</h1>
    <br>
      <div class="d-flex align-items-start justify-contents-top">
        <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12" >
          <div class="p-4 mb-3 card swap-card">
            <p><%= image_tag @listing.game.cover_image, alt: "alttext", class:"card-cover-image pt-3"%></p>
            <h5><%= @listing.game.title %></h5>
            <p><%= @listing.game.description %></p>
            <p><%= @listing.game.console %></p>
          </div>
        </div>

        <div class="p-4 mb-3 mr-3 col-lg-9 col-md-6 col-sm-12 col-xs-12">
          <h3>Make an offer</h3>
          <%= simple_form_for [@listing, @swap] do |f| %>
            <%= f.association :listing_offered, collection: current_user.listings %>
            <%= f.submit "Make Swap Offer", class: "button-blue"%>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/wishlist_items/index.html.erb
<div class="container">
  <h1 class="find-games"> My Wishlist</h1>
  <br>

  <div class="row justify-content-left mb-4">
    <% current_user.wishlist_items.each do |wlitem| %>
      <div class="card-product listing-card">
        <%= image_tag wlitem.game.cover_image, alt: "alttext", class:"card-cover-image"%>
        <div class="card-product-infos">
          <h5 class="game-title"><%= wlitem.game.title %></h5>
        <!--rating algo ends-->
          <p class="console-type"><%=wlitem.game.console %></p>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to "Browse Games", games_path, class: "button-orange mr-3" %>

</div>